### ISSUE TITLE
Dataset availability

### ISSUE THREAD

**Issue by arun-sub** [compbiomed/curatedTBData#42]
Thank you for curating these TB transcriptomic datasets. I tried using the tool, but it looks like the studies are not available yet. 
```
> curatedTBData("GSE79362", dryrun = FALSE, curated.only = FALSE)
snapshotDate(): 2021-05-18
Error: The input "study_name": GSE79362 is/are not available.
```
Any idea when you plan to make the datasets available ? Looking forward to your updates.

--Arun

**Comment by xutao-wang** [comment]
Hi Arun,

Thanks for reaching out! 
To access the data, you might have to update your Bioconductor version to 3.14 so that `snapshotDate()` will be up-to-date. Please notice that this version is currently under development and will be released soon.

Thanks,
Xutao

**Comment by arun-sub** [comment]
Thank you very much! That fixes it. Looking forward to your release.
